apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: atlas
  labels:
    app: auth
    tier: backend
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        tier: backend
        version: v1
    spec:      
      terminationGracePeriodSeconds: 30      
      containers:
      - name: auth
        image: nitros64/auth-service:1.0.11
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
          - name: JAVA_TOOL_OPTIONS
            value: >-
              -XX:+UseContainerSupport
              -XX:MaxRAMPercentage=40.0
              -XX:InitialRAMPercentage=10.0
              -XX:MaxMetaspaceSize=128m  
        envFrom:
          - configMapRef: #DB
              name: cm-auth-spring-datasource
          - configMapRef:
              name: cm-redis    
          - configMapRef:
              name: cm-auth 
          - secretRef:
              name: auth-secret      
          - secretRef:
              name: jwt-secret
          - secretRef:
              name: redis-secret       
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false            
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
            
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 30

        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 6 

        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]  
