apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-order
  namespace: atlas
spec:
  serviceName: postgres-order
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: postgres-order
  template:
    metadata:
      labels:
        app: postgres-order
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres-order
        image: postgres:16
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 5432
          name: postgres

        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-order-secret
              key: POSTGRES_DB

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-order-secret
              key: POSTGRES_USER

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-order-secret
              key: POSTGRES_PASSWORD

        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: standard
      resources:
        requests:
          storage: 2Gi