apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pricing-service-netpol
  namespace: atlas
spec:
  podSelector:
    matchLabels:
      app: pricing
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: atlas
      ports:
        - protocol: TCP
          port: 8086
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53