auth:
  enabled: false

catalog:
  enabled: false

gateway:
  enabled: false

redis:
  enabled: false

kafka:
  enabled: false

postgres:
  enabled: false

cart:
  enabled: false  

pricing:
  enabled: false

coupon:
  enabled: false  

inventory:
  enabled: false  

payment:
  enabled: false  

order:
  enabled: false  

shipping:
  enabled: false  

notification:
  enabled: false  

audit:
  enabled: false