auth:
  enabled: false

catalog:
  enabled: false

gateway:
  enabled: false

redis:
  enabled: false

kafka:
  enabled: false

postgres:
  enabled: false

cart:
  enabled: false  

pricing:
  enabled: false