apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-order
  namespace: atlas
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-order:5432/orderdb
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_RABBITMQ_HOST: rabbitmq-svc
  SPRING_RABBITMQ_PORT: "5672"