server.port=8084

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

security.jwt.secret=${SECURITY_JWT_SECRET}

management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

management.health.redis.enabled=false
management.health.rabbit.enabled=false
management.health.kafka.enabled=false