spring.application.name=inventory-service
server.port=${SERVER_PORT:8084}

#security.jwt.secret=${SECURITY_JWT_SECRET:9P6jcBxWjc9PSAyV5kL21aA6Y1Y1ijlcONXazdXRWf+UHWJWpjPj7nlWTHq0fjKSOKJyt9NaV7Z7AQmW60B2D2hjd9m3/emdO5Aa7aNjVxpzKWvld6EepPDWlTsfpV4l}

# spring.datasource.url=jdbc:h2:mem:inventorydb
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# management.health.redis.enabled=false
# management.health.rabbit.enabled=false
# management.health.kafka.enabled=false