{{- if .Values.pricing.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-pricing
  namespace: {{ .Release.Namespace }}
data:
  SPRING_PROFILES_ACTIVE: "docker"
  SERVER_PORT: {{ .Values.pricing.deployment.containerPort | quote }}
  
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: {{ .Values.runtime.datasource.hikari.maximumPoolSize | quote }}
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: {{ .Values.runtime.datasource.hikari.minimumIdle | quote }}
  SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: {{ .Values.runtime.datasource.hikari.connectionTimeout | quote }}
  
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: {{ .Values.pricing.management.healthProbesEnabled | quote }}
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: {{ .Values.pricing.management.healthShowDetails | quote }}
{{- end }}