#version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - atlas-network

  postgres-auth:
    image: postgres:16
    container_name: postgres-auth
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atlas -d authdb"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - atlas-network

  postgres-catalog:
    image: postgres:16
    container_name: postgres-catalog
    environment:
      POSTGRES_DB: catalogdb
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas
    ports:
      - "5434:5432"
    volumes:
      - postgres_catalog_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atlas -d catalogdb"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - atlas-network

  postgres-order:
    image: postgres:16
    container_name: postgres-order
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas
    ports:
      - "5435:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atlas -d orderdb"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - atlas-network

  auth-service:
    build:
      context: ../../services/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"
    depends_on:
      postgres-auth:
        condition: service_healthy
    networks:
      - atlas-network

  catalog-service:
    build:
      context: ../../services/catalog-service
      dockerfile: Dockerfile
    container_name: catalog-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"
    depends_on:
      postgres-catalog:
        condition: service_healthy
    networks:
      - atlas-network

  order-service:
    build:
      context: ../../services/order-service
      dockerfile: Dockerfile
    container_name: order-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8083:8083"
    depends_on:
      postgres-order:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - atlas-network

volumes:
  postgres_auth_data:
  postgres_catalog_data:
  postgres_order_data:

networks:
  atlas-network:
    driver: bridge
