{{- if and .Values.secretManagement.externalSecrets.enabled .Values.secretManagement.externalSecrets.secretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretManagement.externalSecrets.secretStore.name }}
spec:
  provider:
    aws:
      service: {{ .Values.secretManagement.externalSecrets.secretStore.service | default "SecretsManager" }}
      region: {{ .Values.secretManagement.externalSecrets.secretStore.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.secretManagement.externalSecrets.secretStore.serviceAccountName }}
            namespace: {{ .Values.secretManagement.externalSecrets.secretStore.serviceAccountNamespace }}
{{- end }}