{{- if and .Values.secretManagement.externalSecrets.enabled .Values.secretManagement.externalSecrets.secrets.jwt.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.jwt.name }}-external
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.secretManagement.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.secretManagement.externalSecrets.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secrets.jwt.name }}
    creationPolicy: Owner
  data:
    - secretKey: SECURITY_JWT_SECRET
      remoteRef:
        key: {{ .Values.secretManagement.externalSecrets.secrets.jwt.remoteKey | quote }}
        property: {{ .Values.secretManagement.externalSecrets.secrets.jwt.property | quote }}
{{- end }}