apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: atlas
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
          - redis-server --requirepass "$REDIS_PASSWORD" --appendonly yes
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: redis-data
          mountPath: /data
        
        # Probes  
        startupProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli --no-auth-warning -a "$REDIS_PASSWORD" ping | grep PONG
            failureThreshold: 30
            periodSeconds: 2  
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - redis-cli -a "$REDIS_PASSWORD" ping | grep PONG
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - redis-cli -a "$REDIS_PASSWORD" ping | grep PONG
          initialDelaySeconds: 15
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi