spring.application.name=shipping-service
server.port=8089

security.jwt.secret=9P6jcBxWjc9PSAyV5kL21aA6Y1Y1ijlcONXazdXRWf+UHWJWpjPj7nlWTHq0fjKSOKJyt9NaV7Z7AQmW60B2D2hjd9m3/emdO5Aa7aNjVxpzKWvld6EepPDWlTsfpV4l

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.flyway.enabled=false

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=shipping-service-v1
spring.kafka.consumer.auto-offset-reset=latest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

atlas.kafka.topics.payment-events=${PAYMENT_EVENTS_TOPIC:payment-events}
atlas.kafka.topics.shipping-events=${SHIPPING_EVENTS_TOPIC:shipping-events}

logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=WARN
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF