apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmaps
  - secrets
  - databases/auth
  - databases/catalog
  - databases/order
  - redis
  - messaging/kafka
  - messaging/rabbitmq
  - services/auth
  - services/catalog
  - services/order
  - ingress
  - observability/prometheus
  - observability/grafana