apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmaps
  - secrets
  - databases/auth
  - databases/catalog
  - databases/order
  - redis
  - messaging/kafka
  - messaging/rabbitmq
  - services/auth
  - services/catalog
  - services/order
  - services/gateway
  - services/inventory
  - services/payment
  - services/shipping
  - services/notification
  - services/pricing
  - services/audit
  - services/cart
  - ingress
  - observability/prometheus
  - observability/grafana
  - observability/tempo
  # - network-policies