spring.application.name=catalog-service
server.port=8082

# Postgres - Local
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/catalogdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:atlas}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:atlas}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

# Redis - Local
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:atlas}

# Lettuce Pool - Local
spring.data.redis.lettuce.pool.max-active=10
spring.data.redis.lettuce.pool.max-idle=5
spring.data.redis.lettuce.pool.min-idle=1
spring.data.redis.lettuce.pool.max-wait=2000ms
spring.data.redis.timeout=2000ms

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.endpoint.prometheus.access=unrestricted

# JWT - Local
security.jwt.secret=${SECURITY_JWT_SECRET:dev-local-secret-change-me}

# Kafka - Local
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.group-id=catalog-service-local
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.atlascommerce.catalog.event,com.atlascommerce.order.event
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.atlascommerce.catalog.event.OrderCreatedEvent

atlas.kafka.topics.order-events=${ORDER_EVENTS_TOPIC:order-events}

# Logging
logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%X{correlationId}] [%thread] %logger{36} - %msg%n
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=WARN
logging.level.org.apache.kafka.clients.consumer=WARN