# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# resources:
#   - 00-default-deny.yaml
#   - 01-allow-dns.yaml
#   - 02-allow-ingress-nginx-to-services.yaml
#   - 03-allow-service-to-service.yaml
#   - 04-allow-postgres.yaml
#   - 05-allow-redis.yaml
#   - 06-allow-messaging.yaml
#   - 07-allow-backends-egress.yaml
#   - 08-allow-prometheus-to-backends.yaml