{{- if and .Values.auth.enabled .Values.secretManagement.createByHelm }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.instances.auth.password | quote }}
{{- end }}