spring.application.name=coupon-service
server.port=8087

security.jwt.secret=9P6jcBxWjc9PSAyV5kL21aA6Y1Y1ijlcONXazdXRWf+UHWJWpjPj7nlWTHq0fjKSOKJyt9NaV7Z7AQmW60B2D2hjd9m3/emdO5Aa7aNjVxpzKWvld6EepPDWlTsfpV4l