spring.application.name=coupon-service
server.port=${SERVER_PORT:8087}

security.jwt.secret=${SECURITY_JWT_SECRET:atlas-commerce-dev-secret-1234567890}

# Postgres - Local
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5440/coupondb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:atlas}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:atlas}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

management.health.redis.enabled=false
management.health.rabbit.enabled=false
management.health.kafka.enabled=false

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE