{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.service.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  type: {{ .Values.kafka.service.type }}
  selector:
    app: {{ .Values.kafka.labels.app }}
  ports:
    - name: broker
      port: {{ .Values.kafka.service.brokerPort }}
      targetPort: {{ .Values.kafka.service.brokerPort }}
    - name: controller
      port: {{ .Values.kafka.service.controllerPort }}
      targetPort: {{ .Values.kafka.service.controllerPort }}
{{- end }}
