---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: atlas
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "atlas-microservices"
        metrics_path: "/actuator/prometheus"
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - atlas
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: "^(auth|catalog|order)$"
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "^(8081|8082|8083)$"
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace

      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]