{{- if .Values.postgres.enabled }}
{{- range $key, $db := .Values.postgres.instances }}
{{- if $db.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $db.secretName }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ $db.username | quote }}
  POSTGRES_PASSWORD: {{ $db.password | quote }}
  POSTGRES_DB: {{ $db.database | quote }}
{{- end }}
{{- end }}
{{- end }}