{{- if or .Values.redis.enabled .Values.redis.external.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-redis
  namespace: {{ .Release.Namespace }}
data:
  SPRING_DATA_REDIS_HOST: {{ default .Values.redis.name .Values.redis.external.host | quote }}
  SPRING_DATA_REDIS_PORT: {{ default .Values.redis.service.port .Values.redis.external.port | quote }}
{{- end }}