apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-secret.yaml
  - jwt-secret.yaml
  - postgres-auth-secret.yaml
  - postgres-catalog-secret.yaml
  - postgres-order-secret.yaml
  - rabbitmq-secret.yaml
  - redis-secret.yaml