apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: atlas
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
        tier: backend
        version: v1
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: order
        image: nitros64/order-service:1.0.27
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
          name: http
        envFrom:
        - configMapRef:
            name: cm-order  
        - configMapRef:
            name: cm-redis  
        - configMapRef:
            name: cm-kafka
                
        env:
        - name: JAVA_TOOL_OPTIONS
          value: >-
            -XX:+UseContainerSupport
            -XX:MaxRAMPercentage=35.0
            -XX:InitialRAMPercentage=8.0
            -XX:MaxMetaspaceSize=192m

        # DB
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-order-secret
              key: POSTGRES_USER

        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-order-secret
              key: POSTGRES_PASSWORD

        # Redis
        - name: SPRING_DATA_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD  

        # JWT
        - name: SECURITY_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: SECURITY_JWT_SECRET      

        # RABBITMQ
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_USER

        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_PASS        

        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 45

        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8083
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5

        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8083
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 6
