apiVersion: v1
kind: Secret
metadata:
  name: postgres-notification-secret
type: Opaque
stringData:
  POSTGRES_DB: notificationdb
  POSTGRES_USER: notification
  POSTGRES_PASSWORD: notification123
  SPRING_DATASOURCE_PASSWORD: notification123
