spring.application.name=order-service

server.port=8083

spring.datasource.url=jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
app.rabbitmq.exchange=atlas.orders.exchange
app.rabbitmq.routing-key=orders.created

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
atlas.kafka.topics.order-events=${ORDER_EVENTS_TOPIC:order-events}
spring.kafka.producer.properties.spring.json.add.type.headers=false


atlas.kafka.topics.inventory-events-dlt=${INVENTORY_EVENTS_DLT_TOPIC:inventory-events.DLT}
atlas.kafka.topics.payment-events-dlt=${PAYMENT_EVENTS_DLT_TOPIC:payment-events.DLT}
atlas.kafka.topics.shipping-events-dlt=${SHIPPING_EVENTS_DLT_TOPIC:shipping-events.DLT}

security.jwt.secret=9P6jcBxWjc9PSAyV5kL21aA6Y1Y1ijlcONXazdXRWf+UHWJWpjPj7nlWTHq0fjKSOKJyt9NaV7Z7AQmW60B2D2hjd9m3/emdO5Aa7aNjVxpzKWvld6EepPDWlTsfpV4l

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF