apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
data:
  SPRING_PROFILES_ACTIVE: docker
  SERVER_PORT: "8085"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-cart:5432/cartdb
  SPRING_DATASOURCE_USERNAME: cart
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
  MANAGEMENT_HEALTH_REDIS_ENABLED: "false"
  MANAGEMENT_HEALTH_RABBIT_ENABLED: "false"
  MANAGEMENT_HEALTH_KAFKA_ENABLED: "false"