apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-cart
spec:
  serviceName: postgres-cart
  replicas: 1
  selector:
    matchLabels:
      app: postgres-cart
  template:
    metadata:
      labels:
        app: postgres-cart
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:17
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: postgres-cart-secret
          volumeMounts:
            - name: postgres-cart-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - cart
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - cart
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
  volumeClaimTemplates:
    - metadata:
        name: postgres-cart-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi