apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: atlas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        tier: backend
        version: v1
    spec:
      containers:
        - name: gateway
          image: nitros64/api-gateway:1.0.16
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          envFrom:
            - secretRef:
                name: jwt-secret  

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s

            - name: SPRING_DATA_REDIS_HOST
              value: redis

            - name: SPRING_DATA_REDIS_PORT
              value: "6379"  

            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD  

            - name: MANAGEMENT_HEALTH_REDIS_ENABLED
              value: "false"      

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 5