apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.jwt.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SECURITY_JWT_SECRET: {{ .Values.secrets.jwt.value | quote }}