apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: atlas
  labels:
    app: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
        tier: backend
        version: v1
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: catalog
        image: nitros64/catalog-service:1.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
          name: http
        envFrom:
        - configMapRef:
            name: cm-catalog
        - configMapRef:
            name: cm-kafka    
        env:
        - name: JAVA_TOOL_OPTIONS
          value: >-
            -XX:+UseContainerSupport
            -XX:MaxRAMPercentage=40.0
            -XX:InitialRAMPercentage=10.0
            -XX:MaxMetaspaceSize=128m 

        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-catalog-secret
              key: POSTGRES_USER

        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-catalog-secret
              key: POSTGRES_PASSWORD

        - name: SPRING_DATA_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD

        - name: SECURITY_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: SECURITY_JWT_SECRET
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 30

        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8082
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 6
