apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit
  labels:
    app: audit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: audit
        component: backend
    spec:
      containers:
        - name: audit
          image: nitros64/audit-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8093
              name: http
          envFrom:
            - configMapRef:
                name: audit-config
            - secretRef:
                name: postgres-audit-secret
            - secretRef:
                name: jwt-secret
          resources:
            requests:
              cpu: "150m"
              memory: "384Mi"
            limits:
              cpu: "700m"
              memory: "768Mi"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8093
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8093
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8093
            initialDelaySeconds: 10
            periodSeconds: 10
