apiVersion: v1
kind: Secret
metadata:
  name: postgres-audit-secret
type: Opaque
stringData:
  POSTGRES_DB: auditdb
  POSTGRES_USER: audit
  POSTGRES_PASSWORD: audit123
  SPRING_DATASOURCE_PASSWORD: audit123
