{{- if .Values.postgres.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.auth.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
{{- end }}