{{- if .Values.postgres.auth.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-auth
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: postgres-auth
  serviceName: postgres-auth-headless
  replicas: {{ .Values.postgres.auth.replicas }}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres-auth
          image: {{ .Values.postgres.auth.image | quote }}
          imagePullPolicy: {{ .Values.postgres.auth.imagePullPolicy }}
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: {{ .Values.postgres.auth.resources.requests.cpu | quote }}
              memory: {{ .Values.postgres.auth.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.postgres.auth.resources.limits.cpu | quote }}
              memory: {{ .Values.postgres.auth.resources.limits.memory | quote }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.auth.secretName }}
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.auth.secretName }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.auth.secretName }}
                  key: POSTGRES_PASSWORD
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U {{ .Values.postgres.auth.username }} -d {{ .Values.postgres.auth.database }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U {{ .Values.postgres.auth.username }} -d {{ .Values.postgres.auth.database }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.postgres.auth.persistence.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.postgres.auth.persistence.size }}
{{- end }}