{{- if .Values.cart.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-cart
  namespace: {{ .Release.Namespace }}
data:
  SPRING_PROFILES_ACTIVE: "docker"
  SERVER_PORT: {{ .Values.cart.deployment.containerPort | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.cart.datasource.url | quote }}
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: {{ .Values.cart.datasource.driverClassName | quote }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: {{ .Values.cart.datasource.ddlAuto | quote }}
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: {{ .Values.cart.management.healthProbesEnabled | quote }}
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: {{ .Values.cart.management.healthShowDetails | quote }}
  MANAGEMENT_HEALTH_REDIS_ENABLED: {{ .Values.cart.management.healthRedisEnabled | quote }}
  MANAGEMENT_HEALTH_RABBIT_ENABLED: {{ .Values.cart.management.healthRabbitEnabled | quote }}
  MANAGEMENT_HEALTH_KAFKA_ENABLED: {{ .Values.cart.management.healthKafkaEnabled | quote }}
{{- end }}