spring.application.name=pricing-service
server.port=${SERVER_PORT:8086}

security.jwt.secret=${SECURITY_JWT_SECRET:dev-local-secret-change-me}

spring.jpa.open-in-view=false
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

management.health.redis.enabled=false
management.health.rabbit.enabled=false
management.health.kafka.enabled=false

logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE