apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: payment
        component: backend
    spec:
      containers:
        - name: payment
          image: nitros64/payment-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
              name: http
          envFrom:
            - configMapRef:
                name: payment-config
            - secretRef:
                name: postgres-payment-secret
            - secretRef:
                name: jwt-secret
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8088
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8088
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "150m"
              memory: "384Mi"
            limits:
              cpu: "700m"
              memory: "768Mi"
