apiVersion: v1
kind: Secret
metadata:
  name: postgres-shipping-secret
type: Opaque
stringData:
  POSTGRES_DB: shippingdb
  POSTGRES_USER: shipping
  POSTGRES_PASSWORD: shipping123
  SPRING_DATASOURCE_PASSWORD: shipping123
