apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
        component: backend
    spec:
      containers:
        - name: inventory
          image: nitros64/inventory-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
              name: http
          envFrom:
            - configMapRef:
                name: inventory-config
            - secretRef:
                name: inventory-secret
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "150m"
              memory: "384Mi"
            limits:
              cpu: "700m"
              memory: "768Mi"