apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
data:
  SPRING_PROFILES_ACTIVE: k8s
  SERVER_PORT: "8084"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-inventory:5432/inventorydb
  SPRING_DATASOURCE_USERNAME: inventory
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
  MANAGEMENT_HEALTH_REDIS_ENABLED: "false"
  MANAGEMENT_HEALTH_RABBIT_ENABLED: "false"
  MANAGEMENT_HEALTH_KAFKA_ENABLED: "false"