apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: atlas  
  labels:
    app: inventory
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
        component: backend
    spec:
      containers:
        - name: inventory
          image: nitros64/inventory-service:1.0.13
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
              name: http

          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -XX:+UseContainerSupport
                -XX:MaxRAMPercentage=35.0
                -XX:InitialRAMPercentage=8.0
                -XX:MaxMetaspaceSize=128m   

          envFrom:
            - configMapRef:
                name: inventory-config
            - secretRef:
                name: inventory-secret
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 30

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"