name: Cart Service CI

on:
  push:
    branches: [master, main, develop]
    paths:
      - "services/cart-service/**"
      - ".github/workflows/reusable-service-ci.yml"
  pull_request:
    branches: [master, main, develop]
    paths:
      - "services/cart-service/**"
      - ".github/workflows/reusable-service-ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Build and Test Cart Service
    uses: ./.github/workflows/reusable-service-ci.yml
    with:
      service-name: Cart Service
      service-path: services/cart-service
      docker-image-name: cart-service
    #secrets: inherit
